apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-p0
spec:
  config: '{
    "type": "macvlan",
    "master": "enp193s0f0np0",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "169.254.1.1/32",
          "gateway": "169.254.1.1"
        }
      ],
      "routes": []
    },
    "logLevel": "debug",
    "logFile": "/var/log/sf/macvlan-p0.log"
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-p1
spec:
  config: '{
    "type": "macvlan",
    "master": "enp193s0f1np1",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "169.254.1.1/32",
          "gateway": "169.254.1.1"
        }
      ],
      "routes": []
    },
    "logLevel": "debug",
    "logFile": "/var/log/sf/macvlan-p1.log"
  }'
