apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-bf3-p0
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/bf3_sriov_p0
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "sriov-bf3-p0",
    "type": "sriov",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "169.254.1.1/32",
          "gateway": "169.254.1.1"
        }
      ],
      "routes": []
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-bf3-p1
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/bf3_sriov_p1
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "sriov-bf3-p1",
    "type": "sriov",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "169.254.1.1/32",
          "gateway": "169.254.1.1"
        }
      ],
      "routes": []
    }
  }'
