apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList": [
        {
          "resourceName": "bf3_p0_vf",
          "resourcePrefix": "nvidia.com",
           "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "pfNames": ["enp193s0f0np0"]
            }
        },
        {
          "resourceName": "bf3_p1_vf",
          "resourcePrefix": "nvidia.com",
           "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "pfNames": ["enp193s0f1np1"]
            }
        },
        {
          "resourceName": "bf3_p0_sf",
          "resourcePrefix": "nvidia.com",
          "deviceType": "auxNetDevice",
          "selectors": [{
            "vendors": ["15b3"],
            "devices": ["a2dc"],
            "pciAddresses": ["0000:03:00.0"],
            "pfNames": ["p0#1"],
            "auxTypes": ["sf"]
          }]
        },
        {
          "resourceName": "bf3_p1_sf",
          "resourcePrefix": "nvidia.com",
          "deviceType": "auxNetDevice",
          "selectors": [{
            "vendors": ["15b3"],
            "devices": ["a2dc"],
            "pciAddresses": ["0000:03:00.1"],
            "pfNames": ["p1#1"],
            "auxTypes": ["sf"]
            }]
        }
      ]
    }
