apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "mlnx_sriov_p0",
                "resourcePrefix": "openshift.io",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1018"],
                    "drivers": ["mlx5_core"],
                    "pfNames": ["enp193s0f0np0"],
                    "isRdma": true
                }
            },
            {
                "resourceName": "mlnx_sriov_p1",
                "resourcePrefix": "openshift.io",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1018"],
                    "drivers": ["mlx5_core"],
                    "pfNames": ["enp193s0f1np1"],
                    "isRdma": true
                }
            }
        ]
    }
